text_mining/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    #path('',views.IndexView.as_view()),
    #path('csv/', views.CSVView.as_view()),
]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.PostIndex.as_view(), name='index'),
    path('import/', views.PostImport.as_view(), name='import'),
    path('export/', views.post_export, name='export'),
    path('translate/', views.translate, name='translate'),
]

website/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField('レビュー', max_length=1000)

    def __str__(self):
        return self.title

website/forms.py
import csv
import io
from django import forms
from django.core.validators import FileExtensionValidator
from .models import Post


class TSVUploadForm(forms.Form):
    file = forms.FileField(
        label='TSVファイル',
        help_text='※拡張子tsvのファイルをアップロードしてください。',
        validators=[FileExtensionValidator(allowed_extensions=['tsv'])]
    )

    def clean_file(self):
        file = self.cleaned_data['file']

        # csv.readerに渡すため、TextIOWrapperでテキストモードなファイルに変換
        tsv_file = io.TextIOWrapper(file, encoding='utf-8')
        reader = csv.reader(tsv_file, delimiter='\t')

        # 各行から作った保存前のモデルインスタンスを保管するリスト
        self._instances = []
        try:
            for row in reader:
                post = Post(pk=row[0], title=row[1])
                self._instances.append(post)
        except UnicodeDecodeError:
            raise forms.ValidationError('ファイルのエンコーディングや、正しいTSVファイルか確認ください。')

        return file

    def save(self):
        Post.objects.bulk_create(self._instances, ignore_conflicts=True)
        Post.objects.bulk_update(self._instances, fields=['title'])

website/views.py
import csv
import cgi
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from .forms import TSVUploadForm
from .models import Post
from tkinter import messagebox

# 変換後のデータを格納するリスト
trans_list = []

class PostIndex(generic.ListView):
    model = Post


class PostImport(generic.FormView):
    template_name = 'website/import.html'
    success_url = reverse_lazy('website:index')
    form_class = TSVUploadForm

    def form_valid(self, form):
        form.save()
        return redirect('website:index')
  


def post_export(request):
    response = HttpResponse(content_type='text/tsv')
    response['Content-Disposition'] = 'attachment; filename="translatedList.tsv"'
    # HttpResponseオブジェクトはファイルっぽいオブジェクトなので、csv.writerにそのまま渡せます。
    writer = csv.writer(response, delimiter='\t')
    for post in trans_list:
        writer.writerow([post[0], post[1]])
    return response


def translate(request):
    # response = HttpResponse(content_type='text/tsv')
    # response['Content-Disposition'] = 'attachment; filename="posts.tsv"'
    
    # writer = csv.writer(response, delimiter='\t')

    # file = open('review_list.tsv', 'w')
    # writer = csv.writer(file, delimiter='\t')

    trans_list.clear()


    # 文字列の置換(ここにレビューの変換アルゴリズム書く)
    for post in Post.objects.all():
        if 'こんにちは' in post.title:
            trans_list.append([post.pk, post.title.replace('こんにちは', 'Hello')])
        else:
            trans_list.append([post.pk, post.title])

    params = {
        'trans_list' : trans_list,
        'post_list' : Post.objects.all()
    }

    return render(request, 'website/post_list.html', params)

website/templates/website/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>TSV Upload and Import</title>
  </head>
  <body>
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:import' %}">
          <button type="button" class="btn btn-outline-info">1. Import</button>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:index' %}">
          <button type="button" class="btn btn-outline-info">2. Display</button>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:translate' %}">
          <input type="button" name="translate" value="3. Translate" class="btn btn-outline-info"></input>
          <!-- <button type="button" onclick="translation()" class="btn btn-outline-info">Translate</button> -->
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:export' %}">
          <button type="button" class="btn btn-outline-info">4. Export</button>
        </a>
      </li>
    </ul>
    <div>
      <div class="container" id="left" style="float: left; width: 50%;">
        {% block input %}{% endblock %}
      </div>
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script>
      let left = document.getElementById('left');
      const HTML = `<div class="container" id="right" style="float: right; width: 50%; text-align: left">{% block output %}{% endblock %}</div>`;
      left.insertAdjacentHTML('afterend', HTML);
    </script>

  </body>
</html>

website/templates/website/import.html
{% extends 'website/base.html' %}

{% block input %}
<form action="" method="POST" enctype="multipart/form-data">
  {{ form.as_ul }}
  {% csrf_token %}
  <button type="submit">送信</button>
</form>
{% endblock %}

website/templates/website/post_list.html
{% extends 'website/base.html' %}

{% block input %}
{% if post_list %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>星</th>
      <th>レビュー</th>
    </tr>
  </thead>
  <tbody>   
    {% for post in post_list|slice:":10" %}
      <tr>
        <td>{{ post.pk }}</td>
        <td>{{ post.title}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock %}

{% block output %}
{% if trans_list %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>星</th>
      <th>レビュー</th>
    </tr>
  </thead>
  <tbody>
    {% for post in trans_list|slice:":10" %}
      <tr>
        <td>{{ post.0 }}</td>
        <td>{{ post.1 }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock %}